# Generated by Django 5.2.17 on 2026-09-27 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_profile', models.CharField(max_length=20)),
                ('historical_days', models.PositiveIntegerField(default=365)),
                ('population_size', models.PositiveIntegerField()),
                ('generations', models.PositiveIntegerField()),
                ('expected_return', models.FloatField()),
                ('volatility', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('baseline_return', models.FloatField()),
                ('baseline_volatility', models.FloatField()),
                ('baseline_sharpe_ratio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='portfolios.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='optimizer.optimizationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'symbol'), name='unique_optimization_allocation')],
            },
        ),
    ]
