# Generated by Django 5.2.17 on 2026-09-27 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_horizon', models.PositiveSmallIntegerField()),
                ('loss_tolerance', models.PositiveSmallIntegerField()),
                ('volatility_comfort', models.PositiveSmallIntegerField()),
                ('investment_experience', models.PositiveSmallIntegerField()),
                ('growth_preference', models.PositiveSmallIntegerField()),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('risk_label', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
